version: "3"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: myapp_development
    volumes:
      - ./tmp/db:/var/lib/mysql
  web:
    build: .
    command: bash -c "rm -f /app/tmp/pids/server.pid && rails server -p 3000 -b '0.0.0.0'"
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      MYSQL_HOST: db
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: myapp_development
  vue:
    image: node:14
    command: bash -c "cd /vue && yarn install && yarn serve"
    volumes:
      - ./vue:/vue
    ports:
      - "8080:8080"
    depends_on:
      - web
